/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNICAsyncSocket */

#ifndef _Included_JNICAsyncSocket
#define _Included_JNICAsyncSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNICAsyncSocket
 * Method:    nativeNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_JNICAsyncSocket_nativeNew
  (JNIEnv *, jobject);

/*
 * Class:     JNICAsyncSocket
 * Method:    getSocket
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JNICAsyncSocket_getSocket
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
